### ISSUE TITLE
Broken dice rolls in FVTT 0.7.x

### ISSUE THREAD

**Issue by r-valyar** [Perfectro/forbidden-lands-foundry-vtt#15]
In Foundry VTT 0.7.0 and 0.7.1 dice rolls are broken. Screenshot attached.

![Annotation 2020-08-15 090156](https://user-images.githubusercontent.com/63558984/90306457-21396a80-ded6-11ea-9011-146d79212fa9.jpg)

**Comment by Perfectro** [comment]
Thanks for the feedback.
Alpha & Beta channels are not supported. I will take a look at it for the next stable release.
