### ISSUE TITLE
Rolling from weapon or monster attack display the wrong number of success

### ISSUE THREAD

**Issue by cateland** [Perfectro/forbidden-lands-foundry-vtt#2]
Rolling from weapon or monster attack display the wrong number of success

![image](https://user-images.githubusercontent.com/1081670/84531130-624dac80-ace4-11ea-99e2-a6250714c8ea.png)
![image](https://user-images.githubusercontent.com/1081670/84534344-09811280-acea-11ea-9662-ec97b77c9f78.png)

**Comment by Perfectro** [comment]
Can you show me your monster stat ? I am unable to reproduce it on my part.
Quick reminder. First success count as your number damage. Then each success add 1 damage.

**Comment by Perfectro** [comment]
![image](https://user-images.githubusercontent.com/5683489/84533154-d6d61a80-ace7-11ea-8764-de6c1f88ecc9.png)
Here, work as intended.

**Comment by cateland** [comment]
check your rending attack, show 3 success dice, but resume juste above says 4 success

**Comment by Perfectro** [comment]
Yeah. But 2 damage for the rending attach. First success count as 2. So 4 success.

**Comment by cateland** [comment]
okey those are the damage !
