### ISSUE TITLE
Roll resolution nomenclature

### ISSUE THREAD

**Issue by LyonelMandrake** [Perfectro/forbidden-lands-foundry-vtt#25]
The output of a roll result lists "Damage:" which seems to correspond to the number of successes rolled.  

This has proven to be confusing to players as it does not reflect that what they have actually rolled are successes.  

It is also confusing as should it be the result of an attack roll, it does not reflect the actual damage done as a result of the attack as that is contingent upon the weapon and the number of successes.

Also, the nomenclature the book uses is "Successes".

Thanks for the awesome system!

**Comment by Perfectro** [comment]
Can you provide an example with some screenshot ? I don't have any problems on my end so I don't understand what is the problem on your side.

**Comment by LyonelMandrake** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/31999645/97813247-6efb7e80-1c4c-11eb-9585-f201f3f10e25.png)

That was a stealth roll, there is no damage being done.  There was one Success though.

![image](https://user-images.githubusercontent.com/31999645/97813285-bb46be80-1c4c-11eb-98e3-e095e35965cb.png)

In this case, if that attack was a Battle Axe, the damage done would be three, not two.  There were two successes though.

When the players see the word "Damage" instead of "Success" they think the wrong thing, if that makes sense.

Of course I could be fundamentally misunderstanding the purpose of that text...

**Comment by Perfectro** [comment]
You have to roll from a weapon in order to use the damage.
The damage section is the damage calculated from the roll.
![image](https://user-images.githubusercontent.com/5683489/97815235-e8b35c80-1c8c-11eb-8ce1-4e9d7344bd5c.png)
If you want the success, it's under the skill roll the sword / skull

**Comment by Perfectro** [comment]
Oh, to roll a weapon, do it from the Combat tab.
![image](https://user-images.githubusercontent.com/5683489/97815437-42685680-1c8e-11eb-9970-05b35ecbb473.png)

**Comment by LyonelMandrake** [comment]
Sorry, I guess I am not getting across what I mean. 

When you do a “Roll” of any type the dialog always says “Damage:” regardless of whether or not that roll would result in damage or not. 

It should say “Successes:” instead as that is what the game rules call them. 

Having it always say “Damage:” can be confusing as what it is actually referring to is the number of sixes you rolled which the rules always refer to as “Successes”.

**Comment by Perfectro** [comment]
I know what you mean. The success is always displayed here :
![longbow](https://user-images.githubusercontent.com/5683489/97815847-5497c400-1c91-11eb-9a21-888edba20668.png)
But it is true that the damage field could be shown only on weapon roll.

**Comment by Perfectro** [comment]
The version 3.20.0 display damage only on weapon roll.
![image](https://user-images.githubusercontent.com/5683489/97818960-e1e51380-1ca5-11eb-9ff3-17c6102aebb5.png)
