### ISSUE TITLE
Monster attack

### ISSUE THREAD

**Issue by Faldor1973** [Perfectro/forbidden-lands-foundry-vtt#27]
When creating new monster attacks using entries. Adding digit in damage box do not show up when rolling dice. shows no Damage. Only counting number of successes no base damage are accounted for.
![Screenshot 2020-11-27 155431](https://user-images.githubusercontent.com/75131208/100461281-df20e700-30c8-11eb-86aa-9b0cbada300a.png)

**Comment by Faldor1973** [comment]
Saw an error on my screen take. since no success so no damage. However it do not add success with base damage when damage type other.

**Comment by SlamHammerfist** [comment]
I can't seem to reproduce this. I tried making a new monster attack and adding it to a monster sheet and making a new monster attack from the the monster sheet, it rolls as it should for me both ways.

**Comment by Faldor1973** [comment]
yeah of course it does each additional success after first one adds to damage.... sorry of course think my brain took a freeze pill when entering stuff into Foundry.
Believe we can remove this issue.
