### ISSUE TITLE
Link object bonus to weapon roll

### ISSUE THREAD

**Issue by cateland** [Perfectro/forbidden-lands-foundry-vtt#3]
Bonus dice values described in the weapon could be linked into the roll popup
![image](https://user-images.githubusercontent.com/1081670/84545277-37248680-acff-11ea-93f0-1d9502c22344.png)

**Comment by cateland** [comment]
ok nevermind reading the code i understood how to setup those values, i may propose later a little tutorial for the readme

**Comment by Perfectro** [comment]
Nah, it should do it. I broke it with the last fix related to it.

**Comment by cateland** [comment]
yes just found out that it does work fine combined with an artifact dice but not without it

**Comment by Perfectro** [comment]
Fix on `1.4`.
