### ISSUE TITLE
rollConsumable should display failure on die result 1-2

### ISSUE THREAD

**Issue by maxstar** [Perfectro/forbidden-lands-foundry-vtt#8]
As per consumable rules (Player Handbook, Consumables, page 38) Resource Die decreases on result 1-2. Current logic is as follows:
```
      let die = new Die(consumable.value);
      die.roll(1);
      if (die.total > 1) {
        result = "SUCCEED";
      } else {
        result = "FAILED";
      }
```
Roll of "2" will be considered success which is incorrect.

**Comment by Perfectro** [comment]
Nice catch. Fixed it on 3.4
